### ISSUE TITLE
문제 해결 요청 :: 백준 5598

### ISSUE THREAD

**Issue by SeJonJ** [kimregular/hanghae99-algo#14]
백준 5598 문제 해결 요청합니다

해결 방법이랑 코드랑 상세하게 주석달아서 부탁드립니다(_ _)

acmicpc.net/problem/5598

**Comment by kimregular** [comment]
https://github.com/kimregular/hanghae99-algo/blob/main/src/p5598/Main.java

해당 문제 해결하여 코드 링크를 첨부합니다.
